env: "local" #dev/prod

migration_path: "/home/hobonail/go_projects/docker-pinger/backend/migrations"

storage:
  host: "localhost"
  port: 5432
  username: "postgres"
  dbname: "docker_pinger"

server:
  host: "localhost"
  port: 9999
  timeout: 10s
pinger_api:
  host: "localhost"
  port: 8888
  post_endpoint: "/pinger/ping"
  delete_endpoint: "/pinger/ping"