FROM golang:latest

RUN mkdir /app
WORKDIR /app
ENV BACKEND_CONFIG_PATH=./configs/remote.yaml
ENV POSTGRES_PASS=admin

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main ./cmd/backend/main.go
CMD [ "./main" ]