env: "prod"
delta: 10s

server:
  host: "192.168.1.5"
  port: 8888
  timeout: 10s

client:
  host: "0.0.0.0"
  port: 9999
  get_endpoint: "/backend/containers"
  post_endpoint: "/backend/pings"

redis:
  host: "0.0.0.0"
  port: 6000
  db: 1
  exp: 48h