env: "local"
delay: 5s

server:
  host: "localhost"
  port: 8888
  timeout: 10s

client:
  host: "localhost"
  port: 9999
  get_endpoint: "/backend/containers"
  post_endpoint: "/backend/pings"

redis:
  host: "localhost"
  port: 6379
  db: 1
  exp: 48h